//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WheelyRev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int cartId { get; set; }
        public Nullable<int> productID { get; set; }
        public Nullable<int> shopId { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> statusId { get; set; }
        public string username { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Shops Shops { get; set; }
        public virtual Users Users { get; set; }
        public virtual Status Status { get; set; }
    }
}
