//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WheelyRev.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WheelyRevEntities : DbContext
    {
        public WheelyRevEntities()
            : base("name=WheelyRevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<vw_UserRoles> vw_UserRoles { get; set; }
        public virtual DbSet<Shops> Shops { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Transaction> Transaction { get; set; }
        public virtual DbSet<Cart> Cart { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<vw_GetStatus> vw_GetStatus { get; set; }
        public virtual DbSet<vw_CartItem> vw_CartItem { get; set; }
    
        public virtual int sp_DefaultRole(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DefaultRole", userIdParameter);
        }
    
        public virtual int sp_UpdateRole(Nullable<int> userId, Nullable<int> roleId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("roleId", roleId) :
                new ObjectParameter("roleId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateRole", userIdParameter, roleIdParameter);
        }
    
        public virtual int sp_UpdateShop(Nullable<int> userId, Nullable<int> roleId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("roleId", roleId) :
                new ObjectParameter("roleId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateShop", userIdParameter, roleIdParameter);
        }
    
        public virtual int sp_setShopOwner(Nullable<int> userRoles_ID)
        {
            var userRoles_IDParameter = userRoles_ID.HasValue ?
                new ObjectParameter("userRoles_ID", userRoles_ID) :
                new ObjectParameter("userRoles_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_setShopOwner", userRoles_IDParameter);
        }
    
        public virtual ObjectResult<sp_ProductToBuy_Result> sp_ProductToBuy(Nullable<int> productID)
        {
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("productID", productID) :
                new ObjectParameter("productID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ProductToBuy_Result>("sp_ProductToBuy", productIDParameter);
        }
    
        public virtual ObjectResult<sp_Purchase_Result> sp_Purchase(Nullable<int> productID)
        {
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("productID", productID) :
                new ObjectParameter("productID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Purchase_Result>("sp_Purchase", productIDParameter);
        }
    
        public virtual ObjectResult<sp_BuyNow_Result> sp_BuyNow(Nullable<int> productId)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BuyNow_Result>("sp_BuyNow", productIdParameter);
        }
    
        public virtual int sp_UpdateQty(Nullable<int> quantity, Nullable<int> productID)
        {
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("quantity", quantity) :
                new ObjectParameter("quantity", typeof(int));
    
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("productID", productID) :
                new ObjectParameter("productID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateQty", quantityParameter, productIDParameter);
        }
    
        public virtual ObjectResult<sp_CartDisplay_Result> sp_CartDisplay()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CartDisplay_Result>("sp_CartDisplay");
        }
    
        public virtual ObjectResult<Nullable<int>> sp_MergeQuantity(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_MergeQuantity", userIdParameter);
        }
    
        public virtual ObjectResult<sp_CartItems_Result> sp_CartItems(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CartItems_Result>("sp_CartItems", userIdParameter);
        }
    
        public virtual int sp_UpdateCart(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateCart", userIdParameter);
        }
    }
}
