//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WheelyRev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_GetStatus
    {
        public int statusId { get; set; }
        public Nullable<int> OrderStatus { get; set; }
        public string Order_status { get; set; }
    }
}
